spring.application.name=newproject
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${PORT:8080}
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
# Twilio Credentials (Get these from your Twilio Console)
# This helps you see the database queries in the console for debugging
