spring.application.name=newproject
spring.data.mongodb.uri=mongodb://localhost:27017/user_auth_db
server.port=5096
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akavi6265@gmail.com
spring.mail.password=irkr akpj kpin uxul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio Credentials (Get these from your Twilio Console)
# This helps you see the database queries in the console for debugging
